import { db } from "@workspace/db";
import {
  settingsTable, adminUsersTable,
  packagesTable, activitiesTable, galleryTable,
  blogPostsTable, otpCodesTable,
  bookingsTable, inquiriesTable,
  chatSessionsTable, chatMessagesTable,
  awardsTable, faqsTable, eventsTable,
} from "@workspace/db";

type DbType = "postgresql" | "mysql";

function escStr(val: unknown, dbType: DbType): string {
  if (val === null || val === undefined) return "NULL";
  const s = String(val).replace(/\\/g, "\\\\").replace(/'/g, "''");
  return `'${s}'`;
}

function escBool(val: unknown, dbType: DbType): string {
  if (val === null || val === undefined) return "NULL";
  if (dbType === "mysql") return val ? "1" : "0";
  return val ? "TRUE" : "FALSE";
}

function escJson(val: unknown, dbType: DbType): string {
  if (val === null || val === undefined) return "NULL";
  const s = JSON.stringify(val).replace(/\\/g, "\\\\").replace(/'/g, "''");
  return `'${s}'`;
}

function escArray(val: unknown, dbType: DbType): string {
  if (val === null || val === undefined) return "NULL";
  if (dbType === "mysql") return escJson(val, dbType);
  if (!Array.isArray(val)) return "'{}'";
  if (val.length === 0) return "'{}'";
  const items = val.map((v) => String(v).replace(/\\/g, "\\\\").replace(/"/g, '\\"'));
  return `'{"${items.join('","')}"}'`;
}

function escDate(val: unknown, dbType: DbType): string {
  if (val === null || val === undefined) return "NULL";
  const d = val instanceof Date ? val : new Date(String(val));
  if (isNaN(d.getTime())) return "NULL";
  if (dbType === "mysql") {
    return `'${d.toISOString().replace("T", " ").slice(0, 19)}'`;
  }
  return `'${d.toISOString()}'`;
}

const PG_SCHEMA = `-- ============================================================
--  Shubhangi The Boat House — PostgreSQL Schema
--  Generated by Admin Panel Export
-- ============================================================

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

-- -----------------------------------------------------------
-- admin_users
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS admin_users (
  id            SERIAL PRIMARY KEY,
  username      TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role          TEXT NOT NULL DEFAULT 'admin',
  display_name  TEXT NOT NULL DEFAULT '',
  email         TEXT NOT NULL DEFAULT '',
  phone         TEXT NOT NULL DEFAULT '',
  created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- -----------------------------------------------------------
-- settings
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS settings (
  id                      SERIAL PRIMARY KEY,
  site_name               TEXT NOT NULL DEFAULT 'Goa Houseboat',
  tagline                 TEXT NOT NULL DEFAULT 'Luxury Floating Experience in Goa',
  hero_title              TEXT NOT NULL DEFAULT 'Experience Goa From The Water',
  hero_subtitle           TEXT NOT NULL DEFAULT '',
  hero_image              TEXT NOT NULL DEFAULT '',
  whatsapp_number         TEXT NOT NULL DEFAULT '919876543210',
  inquiry_email           TEXT NOT NULL DEFAULT '',
  social_instagram        TEXT,
  social_facebook         TEXT,
  social_youtube          TEXT,
  trail_video_url         TEXT,
  trail_title             TEXT NOT NULL DEFAULT 'Our Trail',
  trail_description       TEXT NOT NULL DEFAULT '',
  about_text              TEXT NOT NULL DEFAULT '',
  about_images            TEXT[] NOT NULL DEFAULT '{}',
  site_logo               TEXT NOT NULL DEFAULT '',
  nav_hidden_items        TEXT[] NOT NULL DEFAULT '{}',
  smtp_host               TEXT NOT NULL DEFAULT '',
  smtp_port               TEXT NOT NULL DEFAULT '587',
  smtp_user               TEXT NOT NULL DEFAULT '',
  smtp_pass               TEXT NOT NULL DEFAULT '',
  smtp_from               TEXT NOT NULL DEFAULT '',
  smtp_secure             TEXT NOT NULL DEFAULT 'false',
  notify_email            TEXT NOT NULL DEFAULT '',
  show_chat_widget        TEXT NOT NULL DEFAULT 'true',
  chat_widget_color       TEXT NOT NULL DEFAULT '#10b981',
  chat_widget_alignment   TEXT NOT NULL DEFAULT 'right',
  show_whatsapp_button    TEXT NOT NULL DEFAULT 'true',
  location_map_url        TEXT,
  db_type                 TEXT NOT NULL DEFAULT 'postgresql',
  db_host                 TEXT NOT NULL DEFAULT '',
  db_port                 TEXT NOT NULL DEFAULT '3306',
  db_name                 TEXT NOT NULL DEFAULT '',
  db_user                 TEXT NOT NULL DEFAULT '',
  db_pass                 TEXT NOT NULL DEFAULT '',
  deploy_domain           TEXT NOT NULL DEFAULT '',
  upload_root_path        TEXT NOT NULL DEFAULT '/home/youruser/public_html/uploads',
  updated_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- -----------------------------------------------------------
-- packages
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS packages (
  id               SERIAL PRIMARY KEY,
  name             TEXT NOT NULL,
  description      TEXT NOT NULL,
  price_per_night  TEXT NOT NULL,
  mrp_per_night    TEXT,
  capacity         INTEGER NOT NULL DEFAULT 2,
  inclusions       TEXT[] NOT NULL DEFAULT '{}',
  images           TEXT[] NOT NULL DEFAULT '{}',
  is_active        BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order       INTEGER NOT NULL DEFAULT 0,
  created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- -----------------------------------------------------------
-- activities
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS activities (
  id          SERIAL PRIMARY KEY,
  name        TEXT NOT NULL,
  description TEXT NOT NULL,
  icon        TEXT NOT NULL DEFAULT '⚓',
  image       TEXT,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order  INTEGER NOT NULL DEFAULT 0
);

-- -----------------------------------------------------------
-- gallery
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS gallery (
  id         SERIAL PRIMARY KEY,
  url        TEXT NOT NULL,
  caption    TEXT,
  category   TEXT NOT NULL DEFAULT 'general',
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- -----------------------------------------------------------
-- blog_posts
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS blog_posts (
  id               SERIAL PRIMARY KEY,
  title            TEXT NOT NULL,
  slug             TEXT NOT NULL UNIQUE,
  content          TEXT NOT NULL,
  excerpt          TEXT,
  summary          TEXT,
  author_name      TEXT NOT NULL,
  author_email     TEXT,
  images           TEXT[] NOT NULL DEFAULT '{}',
  hashtags         TEXT[] NOT NULL DEFAULT '{}',
  links            TEXT[] NOT NULL DEFAULT '{}',
  status           TEXT NOT NULL DEFAULT 'pending',
  is_admin_post    BOOLEAN NOT NULL DEFAULT FALSE,
  meta_title       TEXT,
  meta_description TEXT,
  published_at     TIMESTAMP WITH TIME ZONE,
  created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- -----------------------------------------------------------
-- otp_codes
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS otp_codes (
  id         SERIAL PRIMARY KEY,
  email      TEXT NOT NULL,
  code       TEXT NOT NULL,
  token      TEXT,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  verified   BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- -----------------------------------------------------------
-- bookings
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS bookings (
  id           SERIAL PRIMARY KEY,
  guest_name   TEXT NOT NULL,
  guest_email  TEXT NOT NULL,
  guest_phone  TEXT NOT NULL DEFAULT '',
  package_id   INTEGER,
  package_name TEXT NOT NULL DEFAULT '',
  check_in     DATE NOT NULL,
  check_out    DATE NOT NULL,
  guests       INTEGER NOT NULL DEFAULT 2,
  kids         INTEGER NOT NULL DEFAULT 0,
  status       TEXT NOT NULL DEFAULT 'confirmed',
  notes        TEXT DEFAULT '',
  total_price  TEXT DEFAULT '',
  created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- -----------------------------------------------------------
-- inquiries
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS inquiries (
  id              SERIAL PRIMARY KEY,
  name            TEXT NOT NULL,
  email           TEXT NOT NULL,
  phone           TEXT NOT NULL DEFAULT '',
  whatsapp        TEXT NOT NULL DEFAULT '',
  package_service TEXT NOT NULL DEFAULT '',
  check_in        TEXT DEFAULT '',
  check_out       TEXT DEFAULT '',
  guests          INTEGER DEFAULT 2,
  kids            INTEGER NOT NULL DEFAULT 0,
  pax_details     TEXT NOT NULL DEFAULT '',
  message         TEXT NOT NULL DEFAULT '',
  status          TEXT NOT NULL DEFAULT 'new',
  created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- -----------------------------------------------------------
-- chat_sessions
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS chat_sessions (
  id           SERIAL PRIMARY KEY,
  token        TEXT NOT NULL UNIQUE,
  visitor_name TEXT NOT NULL DEFAULT 'Guest',
  status       TEXT NOT NULL DEFAULT 'active',
  created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- -----------------------------------------------------------
-- chat_messages
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS chat_messages (
  id         SERIAL PRIMARY KEY,
  session_id INTEGER NOT NULL,
  sender     TEXT NOT NULL,
  message    TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_chat_session FOREIGN KEY (session_id) REFERENCES chat_sessions(id) ON DELETE CASCADE
);

-- -----------------------------------------------------------
-- awards
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS awards (
  id         SERIAL PRIMARY KEY,
  title      TEXT NOT NULL,
  subtitle   TEXT NOT NULL DEFAULT '',
  image      TEXT,
  link       TEXT,
  is_active  BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order INTEGER NOT NULL DEFAULT 0
);

-- -----------------------------------------------------------
-- faqs
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS faqs (
  id         SERIAL PRIMARY KEY,
  question   TEXT NOT NULL,
  answer     TEXT NOT NULL,
  is_active  BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order INTEGER NOT NULL DEFAULT 0
);

-- -----------------------------------------------------------
-- events
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS events (
  id          SERIAL PRIMARY KEY,
  name        TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  image       TEXT,
  amenities   TEXT NOT NULL DEFAULT '',
  chargeables JSON NOT NULL DEFAULT '[]',
  min_hours   INTEGER NOT NULL DEFAULT 2,
  sort_order  INTEGER NOT NULL DEFAULT 0,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE
);

`;

const MYSQL_SCHEMA = `-- ============================================================
--  Shubhangi The Boat House — MySQL Schema
--  Generated by Admin Panel Export
-- ============================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- -----------------------------------------------------------
-- admin_users
-- -----------------------------------------------------------
DROP TABLE IF EXISTS \`admin_users\`;
CREATE TABLE \`admin_users\` (
  \`id\`            INT NOT NULL AUTO_INCREMENT,
  \`username\`      LONGTEXT NOT NULL,
  \`password_hash\` LONGTEXT NOT NULL,
  \`role\`          LONGTEXT NOT NULL DEFAULT 'admin',
  \`display_name\`  LONGTEXT NOT NULL DEFAULT '',
  \`email\`         LONGTEXT NOT NULL DEFAULT '',
  \`phone\`         LONGTEXT NOT NULL DEFAULT '',
  \`created_at\`    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`admin_users_username_unique\` ((substring(\`username\`,1,255)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------------
-- settings
-- -----------------------------------------------------------
DROP TABLE IF EXISTS \`settings\`;
CREATE TABLE \`settings\` (
  \`id\`                      INT NOT NULL AUTO_INCREMENT,
  \`site_name\`               LONGTEXT NOT NULL DEFAULT 'Goa Houseboat',
  \`tagline\`                 LONGTEXT NOT NULL,
  \`hero_title\`              LONGTEXT NOT NULL,
  \`hero_subtitle\`           LONGTEXT NOT NULL,
  \`hero_image\`              LONGTEXT NOT NULL,
  \`whatsapp_number\`         LONGTEXT NOT NULL,
  \`inquiry_email\`           LONGTEXT NOT NULL,
  \`social_instagram\`        LONGTEXT,
  \`social_facebook\`         LONGTEXT,
  \`social_youtube\`          LONGTEXT,
  \`trail_video_url\`         LONGTEXT,
  \`trail_title\`             LONGTEXT NOT NULL,
  \`trail_description\`       LONGTEXT NOT NULL,
  \`about_text\`              LONGTEXT NOT NULL,
  \`about_images\`            JSON NOT NULL,
  \`site_logo\`               LONGTEXT NOT NULL,
  \`nav_hidden_items\`        JSON NOT NULL,
  \`smtp_host\`               LONGTEXT NOT NULL,
  \`smtp_port\`               LONGTEXT NOT NULL,
  \`smtp_user\`               LONGTEXT NOT NULL,
  \`smtp_pass\`               LONGTEXT NOT NULL,
  \`smtp_from\`               LONGTEXT NOT NULL,
  \`smtp_secure\`             LONGTEXT NOT NULL,
  \`notify_email\`            LONGTEXT NOT NULL,
  \`show_chat_widget\`        LONGTEXT NOT NULL,
  \`chat_widget_color\`       LONGTEXT NOT NULL,
  \`chat_widget_alignment\`   LONGTEXT NOT NULL,
  \`show_whatsapp_button\`    LONGTEXT NOT NULL,
  \`location_map_url\`        LONGTEXT,
  \`db_type\`                 LONGTEXT NOT NULL,
  \`db_host\`                 LONGTEXT NOT NULL,
  \`db_port\`                 LONGTEXT NOT NULL,
  \`db_name\`                 LONGTEXT NOT NULL,
  \`db_user\`                 LONGTEXT NOT NULL,
  \`db_pass\`                 LONGTEXT NOT NULL,
  \`deploy_domain\`           LONGTEXT NOT NULL,
  \`upload_root_path\`        LONGTEXT NOT NULL,
  \`updated_at\`              DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------------
-- packages
-- -----------------------------------------------------------
DROP TABLE IF EXISTS \`packages\`;
CREATE TABLE \`packages\` (
  \`id\`               INT NOT NULL AUTO_INCREMENT,
  \`name\`             LONGTEXT NOT NULL,
  \`description\`      LONGTEXT NOT NULL,
  \`price_per_night\`  LONGTEXT NOT NULL,
  \`mrp_per_night\`    LONGTEXT,
  \`capacity\`         INT NOT NULL DEFAULT 2,
  \`inclusions\`       JSON NOT NULL,
  \`images\`           JSON NOT NULL,
  \`is_active\`        TINYINT(1) NOT NULL DEFAULT 1,
  \`sort_order\`       INT NOT NULL DEFAULT 0,
  \`created_at\`       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  \`updated_at\`       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------------
-- activities
-- -----------------------------------------------------------
DROP TABLE IF EXISTS \`activities\`;
CREATE TABLE \`activities\` (
  \`id\`          INT NOT NULL AUTO_INCREMENT,
  \`name\`        LONGTEXT NOT NULL,
  \`description\` LONGTEXT NOT NULL,
  \`icon\`        LONGTEXT NOT NULL DEFAULT '⚓',
  \`image\`       LONGTEXT,
  \`is_active\`   TINYINT(1) NOT NULL DEFAULT 1,
  \`sort_order\`  INT NOT NULL DEFAULT 0,
  PRIMARY KEY (\`id\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------------
-- gallery
-- -----------------------------------------------------------
DROP TABLE IF EXISTS \`gallery\`;
CREATE TABLE \`gallery\` (
  \`id\`         INT NOT NULL AUTO_INCREMENT,
  \`url\`        LONGTEXT NOT NULL,
  \`caption\`    LONGTEXT,
  \`category\`   LONGTEXT NOT NULL DEFAULT 'general',
  \`sort_order\` INT NOT NULL DEFAULT 0,
  \`created_at\` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------------
-- blog_posts
-- -----------------------------------------------------------
DROP TABLE IF EXISTS \`blog_posts\`;
CREATE TABLE \`blog_posts\` (
  \`id\`               INT NOT NULL AUTO_INCREMENT,
  \`title\`            LONGTEXT NOT NULL,
  \`slug\`             VARCHAR(255) NOT NULL,
  \`content\`          LONGTEXT NOT NULL,
  \`excerpt\`          LONGTEXT,
  \`summary\`          LONGTEXT,
  \`author_name\`      LONGTEXT NOT NULL,
  \`author_email\`     LONGTEXT,
  \`images\`           JSON NOT NULL,
  \`hashtags\`         JSON NOT NULL,
  \`links\`            JSON NOT NULL,
  \`status\`           LONGTEXT NOT NULL DEFAULT 'pending',
  \`is_admin_post\`    TINYINT(1) NOT NULL DEFAULT 0,
  \`meta_title\`       LONGTEXT,
  \`meta_description\` LONGTEXT,
  \`published_at\`     DATETIME,
  \`created_at\`       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  \`updated_at\`       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`blog_posts_slug_unique\` (\`slug\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------------
-- otp_codes
-- -----------------------------------------------------------
DROP TABLE IF EXISTS \`otp_codes\`;
CREATE TABLE \`otp_codes\` (
  \`id\`         INT NOT NULL AUTO_INCREMENT,
  \`email\`      LONGTEXT NOT NULL,
  \`code\`       LONGTEXT NOT NULL,
  \`token\`      LONGTEXT,
  \`expires_at\` DATETIME NOT NULL,
  \`verified\`   TINYINT(1) NOT NULL DEFAULT 0,
  \`created_at\` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------------
-- bookings
-- -----------------------------------------------------------
DROP TABLE IF EXISTS \`bookings\`;
CREATE TABLE \`bookings\` (
  \`id\`           INT NOT NULL AUTO_INCREMENT,
  \`guest_name\`   LONGTEXT NOT NULL,
  \`guest_email\`  LONGTEXT NOT NULL,
  \`guest_phone\`  LONGTEXT NOT NULL,
  \`package_id\`   INT,
  \`package_name\` LONGTEXT NOT NULL,
  \`check_in\`     DATE NOT NULL,
  \`check_out\`    DATE NOT NULL,
  \`guests\`       INT NOT NULL DEFAULT 2,
  \`kids\`         INT NOT NULL DEFAULT 0,
  \`status\`       LONGTEXT NOT NULL DEFAULT 'confirmed',
  \`notes\`        LONGTEXT,
  \`total_price\`  LONGTEXT,
  \`created_at\`   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------------
-- inquiries
-- -----------------------------------------------------------
DROP TABLE IF EXISTS \`inquiries\`;
CREATE TABLE \`inquiries\` (
  \`id\`              INT NOT NULL AUTO_INCREMENT,
  \`name\`            LONGTEXT NOT NULL,
  \`email\`           LONGTEXT NOT NULL,
  \`phone\`           LONGTEXT NOT NULL,
  \`whatsapp\`        LONGTEXT NOT NULL,
  \`package_service\` LONGTEXT NOT NULL,
  \`check_in\`        LONGTEXT,
  \`check_out\`       LONGTEXT,
  \`guests\`          INT DEFAULT 2,
  \`kids\`            INT NOT NULL DEFAULT 0,
  \`pax_details\`     LONGTEXT NOT NULL,
  \`message\`         LONGTEXT NOT NULL,
  \`status\`          LONGTEXT NOT NULL DEFAULT 'new',
  \`created_at\`      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------------
-- chat_sessions
-- -----------------------------------------------------------
DROP TABLE IF EXISTS \`chat_sessions\`;
CREATE TABLE \`chat_sessions\` (
  \`id\`           INT NOT NULL AUTO_INCREMENT,
  \`token\`        VARCHAR(255) NOT NULL,
  \`visitor_name\` LONGTEXT NOT NULL DEFAULT 'Guest',
  \`status\`       LONGTEXT NOT NULL DEFAULT 'active',
  \`created_at\`   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  \`updated_at\`   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`chat_sessions_token_unique\` (\`token\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------------
-- chat_messages
-- -----------------------------------------------------------
DROP TABLE IF EXISTS \`chat_messages\`;
CREATE TABLE \`chat_messages\` (
  \`id\`         INT NOT NULL AUTO_INCREMENT,
  \`session_id\` INT NOT NULL,
  \`sender\`     LONGTEXT NOT NULL,
  \`message\`    LONGTEXT NOT NULL,
  \`created_at\` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`),
  CONSTRAINT \`fk_chat_session\` FOREIGN KEY (\`session_id\`) REFERENCES \`chat_sessions\` (\`id\`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------------
-- awards
-- -----------------------------------------------------------
DROP TABLE IF EXISTS \`awards\`;
CREATE TABLE \`awards\` (
  \`id\`         INT NOT NULL AUTO_INCREMENT,
  \`title\`      LONGTEXT NOT NULL,
  \`subtitle\`   LONGTEXT NOT NULL,
  \`image\`      LONGTEXT,
  \`link\`       LONGTEXT,
  \`is_active\`  TINYINT(1) NOT NULL DEFAULT 1,
  \`sort_order\` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (\`id\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------------
-- faqs
-- -----------------------------------------------------------
DROP TABLE IF EXISTS \`faqs\`;
CREATE TABLE \`faqs\` (
  \`id\`         INT NOT NULL AUTO_INCREMENT,
  \`question\`   LONGTEXT NOT NULL,
  \`answer\`     LONGTEXT NOT NULL,
  \`is_active\`  TINYINT(1) NOT NULL DEFAULT 1,
  \`sort_order\` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (\`id\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------------
-- events
-- -----------------------------------------------------------
DROP TABLE IF EXISTS \`events\`;
CREATE TABLE \`events\` (
  \`id\`          INT NOT NULL AUTO_INCREMENT,
  \`name\`        LONGTEXT NOT NULL,
  \`description\` LONGTEXT NOT NULL,
  \`image\`       LONGTEXT,
  \`amenities\`   LONGTEXT NOT NULL,
  \`chargeables\` JSON NOT NULL,
  \`min_hours\`   INT NOT NULL DEFAULT 2,
  \`sort_order\`  INT NOT NULL DEFAULT 0,
  \`is_active\`   TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (\`id\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
`;

function buildInserts(
  tableName: string,
  rows: Record<string, unknown>[],
  colMap: Record<string, (row: Record<string, unknown>, dbType: DbType) => string>,
  dbType: DbType
): string {
  if (rows.length === 0) return "";
  const q = dbType === "mysql" ? "`" : "";
  const cols = Object.keys(colMap).map((c) => `${q}${c}${q}`).join(", ");
  const lines = rows.map((row) => {
    const vals = Object.values(colMap).map((fn) => fn(row, dbType)).join(", ");
    return `(${vals})`;
  });

  const tbl = dbType === "mysql" ? `\`${tableName}\`` : tableName;
  return `\n-- Data: ${tableName}\nINSERT INTO ${tbl} (${cols}) VALUES\n${lines.join(",\n")};\n`;
}

export async function generateSql(dbType: DbType): Promise<string> {
  const schema = dbType === "postgresql" ? PG_SCHEMA : MYSQL_SCHEMA;
  const parts: string[] = [schema, "\n-- ============================================================\n-- DATA\n-- ============================================================\n"];

  const adminUsers = await db.select().from(adminUsersTable);
  parts.push(buildInserts("admin_users", adminUsers, {
    username: (r) => escStr(r.username, dbType),
    password_hash: (r) => escStr(r.passwordHash, dbType),
    role: (r) => escStr(r.role, dbType),
    display_name: (r) => escStr(r.displayName, dbType),
    email: (r) => escStr(r.email, dbType),
    phone: (r) => escStr(r.phone, dbType),
    created_at: (r) => escDate(r.createdAt, dbType),
  }, dbType));

  const settings = await db.select().from(settingsTable);
  parts.push(buildInserts("settings", settings, {
    site_name: (r) => escStr(r.siteName, dbType),
    tagline: (r) => escStr(r.tagline, dbType),
    hero_title: (r) => escStr(r.heroTitle, dbType),
    hero_subtitle: (r) => escStr(r.heroSubtitle, dbType),
    hero_image: (r) => escStr(r.heroImage, dbType),
    whatsapp_number: (r) => escStr(r.whatsappNumber, dbType),
    inquiry_email: (r) => escStr(r.inquiryEmail, dbType),
    social_instagram: (r) => escStr(r.socialInstagram, dbType),
    social_facebook: (r) => escStr(r.socialFacebook, dbType),
    social_youtube: (r) => escStr(r.socialYoutube, dbType),
    trail_video_url: (r) => escStr(r.trailVideoUrl, dbType),
    trail_title: (r) => escStr(r.trailTitle, dbType),
    trail_description: (r) => escStr(r.trailDescription, dbType),
    about_text: (r) => escStr(r.aboutText, dbType),
    about_images: (r) => escArray(r.aboutImages, dbType),
    site_logo: (r) => escStr(r.siteLogo, dbType),
    nav_hidden_items: (r) => escArray(r.navHiddenItems, dbType),
    smtp_host: (r) => escStr(r.smtpHost, dbType),
    smtp_port: (r) => escStr(r.smtpPort, dbType),
    smtp_user: (r) => escStr(r.smtpUser, dbType),
    smtp_pass: (r) => escStr(r.smtpPass, dbType),
    smtp_from: (r) => escStr(r.smtpFrom, dbType),
    smtp_secure: (r) => escStr(r.smtpSecure, dbType),
    notify_email: (r) => escStr(r.notifyEmail, dbType),
    show_chat_widget: (r) => escStr(r.showChatWidget, dbType),
    chat_widget_color: (r) => escStr(r.chatWidgetColor, dbType),
    chat_widget_alignment: (r) => escStr(r.chatWidgetAlignment, dbType),
    show_whatsapp_button: (r) => escStr(r.showWhatsappButton, dbType),
    location_map_url: (r) => escStr(r.locationMapUrl, dbType),
    db_type: (r) => escStr(r.dbType, dbType),
    db_host: (r) => escStr(r.dbHost, dbType),
    db_port: (r) => escStr(r.dbPort, dbType),
    db_name: (r) => escStr(r.dbName, dbType),
    db_user: (r) => escStr(r.dbUser, dbType),
    db_pass: (r) => escStr(r.dbPass, dbType),
    deploy_domain: (r) => escStr(r.deployDomain, dbType),
    upload_root_path: (r) => escStr(r.uploadRootPath, dbType),
    updated_at: (r) => escDate(r.updatedAt, dbType),
  }, dbType));

  const packages = await db.select().from(packagesTable);
  parts.push(buildInserts("packages", packages, {
    name: (r) => escStr(r.name, dbType),
    description: (r) => escStr(r.description, dbType),
    price_per_night: (r) => escStr(r.pricePerNight, dbType),
    mrp_per_night: (r) => escStr(r.mrpPerNight, dbType),
    capacity: (r) => String(r.capacity ?? 2),
    inclusions: (r) => escArray(r.inclusions, dbType),
    images: (r) => escArray(r.images, dbType),
    is_active: (r) => escBool(r.isActive, dbType),
    sort_order: (r) => String(r.sortOrder ?? 0),
    created_at: (r) => escDate(r.createdAt, dbType),
    updated_at: (r) => escDate(r.updatedAt, dbType),
  }, dbType));

  const activities = await db.select().from(activitiesTable);
  parts.push(buildInserts("activities", activities, {
    name: (r) => escStr(r.name, dbType),
    description: (r) => escStr(r.description, dbType),
    icon: (r) => escStr(r.icon, dbType),
    image: (r) => escStr(r.image, dbType),
    is_active: (r) => escBool(r.isActive, dbType),
    sort_order: (r) => String(r.sortOrder ?? 0),
  }, dbType));

  const gallery = await db.select().from(galleryTable);
  parts.push(buildInserts("gallery", gallery, {
    url: (r) => escStr(r.url, dbType),
    caption: (r) => escStr(r.caption, dbType),
    category: (r) => escStr(r.category, dbType),
    sort_order: (r) => String(r.sortOrder ?? 0),
    created_at: (r) => escDate(r.createdAt, dbType),
  }, dbType));

  const blogs = await db.select().from(blogPostsTable);
  parts.push(buildInserts("blog_posts", blogs, {
    title: (r) => escStr(r.title, dbType),
    slug: (r) => escStr(r.slug, dbType),
    content: (r) => escStr(r.content, dbType),
    excerpt: (r) => escStr(r.excerpt, dbType),
    summary: (r) => escStr(r.summary, dbType),
    author_name: (r) => escStr(r.authorName, dbType),
    author_email: (r) => escStr(r.authorEmail, dbType),
    images: (r) => escArray(r.images, dbType),
    hashtags: (r) => escArray(r.hashtags, dbType),
    links: (r) => escArray(r.links, dbType),
    status: (r) => escStr(r.status, dbType),
    is_admin_post: (r) => escBool(r.isAdminPost, dbType),
    meta_title: (r) => escStr(r.metaTitle, dbType),
    meta_description: (r) => escStr(r.metaDescription, dbType),
    published_at: (r) => escDate(r.publishedAt, dbType),
    created_at: (r) => escDate(r.createdAt, dbType),
    updated_at: (r) => escDate(r.updatedAt, dbType),
  }, dbType));

  const bookings = await db.select().from(bookingsTable);
  parts.push(buildInserts("bookings", bookings, {
    guest_name: (r) => escStr(r.guestName, dbType),
    guest_email: (r) => escStr(r.guestEmail, dbType),
    guest_phone: (r) => escStr(r.guestPhone, dbType),
    package_id: (r) => r.packageId == null ? "NULL" : String(r.packageId),
    package_name: (r) => escStr(r.packageName, dbType),
    check_in: (r) => escStr(r.checkIn, dbType),
    check_out: (r) => escStr(r.checkOut, dbType),
    guests: (r) => String(r.guests ?? 2),
    kids: (r) => String(r.kids ?? 0),
    status: (r) => escStr(r.status, dbType),
    notes: (r) => escStr(r.notes, dbType),
    total_price: (r) => escStr(r.totalPrice, dbType),
    created_at: (r) => escDate(r.createdAt, dbType),
  }, dbType));

  const inquiries = await db.select().from(inquiriesTable);
  parts.push(buildInserts("inquiries", inquiries, {
    name: (r) => escStr(r.name, dbType),
    email: (r) => escStr(r.email, dbType),
    phone: (r) => escStr(r.phone, dbType),
    whatsapp: (r) => escStr(r.whatsapp, dbType),
    package_service: (r) => escStr(r.packageService, dbType),
    check_in: (r) => escStr(r.checkIn, dbType),
    check_out: (r) => escStr(r.checkOut, dbType),
    guests: (r) => r.guests == null ? "NULL" : String(r.guests),
    kids: (r) => String(r.kids ?? 0),
    pax_details: (r) => escStr(r.paxDetails, dbType),
    message: (r) => escStr(r.message, dbType),
    status: (r) => escStr(r.status, dbType),
    created_at: (r) => escDate(r.createdAt, dbType),
  }, dbType));

  const awards = await db.select().from(awardsTable);
  parts.push(buildInserts("awards", awards, {
    title: (r) => escStr(r.title, dbType),
    subtitle: (r) => escStr(r.subtitle, dbType),
    image: (r) => escStr(r.image, dbType),
    link: (r) => escStr(r.link, dbType),
    is_active: (r) => escBool(r.isActive, dbType),
    sort_order: (r) => String(r.sortOrder ?? 0),
  }, dbType));

  const faqs = await db.select().from(faqsTable);
  parts.push(buildInserts("faqs", faqs, {
    question: (r) => escStr(r.question, dbType),
    answer: (r) => escStr(r.answer, dbType),
    is_active: (r) => escBool(r.isActive, dbType),
    sort_order: (r) => String(r.sortOrder ?? 0),
  }, dbType));

  const events = await db.select().from(eventsTable);
  parts.push(buildInserts("events", events, {
    name: (r) => escStr(r.name, dbType),
    description: (r) => escStr(r.description, dbType),
    image: (r) => escStr(r.image, dbType),
    amenities: (r) => escStr(r.amenities, dbType),
    chargeables: (r) => escJson(r.chargeables, dbType),
    min_hours: (r) => String(r.minHours ?? 2),
    sort_order: (r) => String(r.sortOrder ?? 0),
    is_active: (r) => escBool(r.isActive, dbType),
  }, dbType));

  if (dbType === "postgresql") {
    parts.push(`\n-- Reset sequences after data import\nSELECT setval('admin_users_id_seq', COALESCE((SELECT MAX(id) FROM admin_users), 0) + 1, false);\nSELECT setval('settings_id_seq', COALESCE((SELECT MAX(id) FROM settings), 0) + 1, false);\nSELECT setval('packages_id_seq', COALESCE((SELECT MAX(id) FROM packages), 0) + 1, false);\nSELECT setval('activities_id_seq', COALESCE((SELECT MAX(id) FROM activities), 0) + 1, false);\nSELECT setval('gallery_id_seq', COALESCE((SELECT MAX(id) FROM gallery), 0) + 1, false);\nSELECT setval('blog_posts_id_seq', COALESCE((SELECT MAX(id) FROM blog_posts), 0) + 1, false);\nSELECT setval('bookings_id_seq', COALESCE((SELECT MAX(id) FROM bookings), 0) + 1, false);\nSELECT setval('inquiries_id_seq', COALESCE((SELECT MAX(id) FROM inquiries), 0) + 1, false);\nSELECT setval('awards_id_seq', COALESCE((SELECT MAX(id) FROM awards), 0) + 1, false);\nSELECT setval('faqs_id_seq', COALESCE((SELECT MAX(id) FROM faqs), 0) + 1, false);\nSELECT setval('events_id_seq', COALESCE((SELECT MAX(id) FROM events), 0) + 1, false);\nSELECT setval('chat_sessions_id_seq', COALESCE((SELECT MAX(id) FROM chat_sessions), 0) + 1, false);\nSELECT setval('chat_messages_id_seq', COALESCE((SELECT MAX(id) FROM chat_messages), 0) + 1, false);\nSELECT setval('otp_codes_id_seq', COALESCE((SELECT MAX(id) FROM otp_codes), 0) + 1, false);\n`);
  }

  parts.push(`\n-- ============================================================\n-- Export complete\n-- ============================================================\n`);
  return parts.join("");
}
