import { pgTable, text, serial, timestamp } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

export const settingsTable = pgTable("settings", {
  id: serial("id").primaryKey(),
  siteName: text("site_name").notNull().default("Goa Houseboat"),
  tagline: text("tagline").notNull().default("Luxury Floating Experience in Goa"),
  heroTitle: text("hero_title").notNull().default("Experience Goa From The Water"),
  heroSubtitle: text("hero_subtitle").notNull().default("Luxury houseboat stay with 3 private bedrooms, rooftop dining, and thrilling water activities"),
  heroImage: text("hero_image").notNull().default(""),
  heroLocationTag: text("hero_location_tag").notNull().default("Mandovi River, Goa"),
  whatsappNumber: text("whatsapp_number").notNull().default("919876543210"),
  inquiryEmail: text("inquiry_email").notNull().default("booking@goahouseboat.com"),
  socialInstagram: text("social_instagram"),
  socialFacebook: text("social_facebook"),
  socialYoutube: text("social_youtube"),
  trailVideoUrl: text("trail_video_url"),
  trailTitle: text("trail_title").notNull().default("Our Trail"),
  trailDescription: text("trail_description").notNull().default("Take a virtual tour of our regular cruise route. Watch as we navigate through mangroves, local fishing villages, and open waters."),
  aboutText: text("about_text").notNull().default("Welcome to our luxury houseboat experience in Goa. Nestled on the serene backwaters, our houseboat offers an unparalleled blend of comfort and adventure. With 3 beautifully appointed bedrooms, a rooftop restaurant with live cooking, and a range of exciting water activities, we promise memories that will last a lifetime."),
  aboutImages: text("about_images").array().notNull().default([]),
  aboutStoryTitle: text("about_story_title").notNull().default("The Floating Haven"),
  aboutStoryParagraph2: text("about_story_paragraph2").notNull().default("We pride ourselves on offering a sustainable yet lavish experience. Our dedicated crew ensures your every need is met, from gourmet dining on the rooftop deck to guiding you through hidden waterways on kayaks."),
  mapDescription: text("map_description").notNull().default("Chapora River, North Goa — Click the map to get directions"),
  siteLogo: text("site_logo").notNull().default(""),
  navHiddenItems: text("nav_hidden_items").array().notNull().default([]),
  smtpHost: text("smtp_host").notNull().default(""),
  smtpPort: text("smtp_port").notNull().default("587"),
  smtpUser: text("smtp_user").notNull().default(""),
  smtpPass: text("smtp_pass").notNull().default(""),
  smtpFrom: text("smtp_from").notNull().default(""),
  smtpSecure: text("smtp_secure").notNull().default("false"),
  notifyEmail: text("notify_email").notNull().default(""),
  showChatWidget: text("show_chat_widget").notNull().default("true"),
  chatWidgetColor: text("chat_widget_color").notNull().default("#10b981"),
  chatWidgetAlignment: text("chat_widget_alignment").notNull().default("right"),
  showWhatsappButton: text("show_whatsapp_button").notNull().default("true"),
  locationMapUrl: text("location_map_url"),
  exploreLabel: text("explore_label").notNull().default("Everything in One Place"),
  exploreTitle: text("explore_title").notNull().default("Explore Mhadeinest's Backwater Experience"),
  exploreSubtitle: text("explore_subtitle").notNull().default("From your first sunrise over the Mandovi to a candle-lit rooftop dinner, every moment aboard Mhadeinest is thoughtfully curated. Choose your experience below."),
  welcomeLabel: text("welcome_label").notNull().default("Welcome Aboard"),
  welcomeTitle: text("welcome_title").notNull().default("A Floating Paradise in the Heart of Goa"),
  welcomeRatingText: text("welcome_rating_text").notNull().default("5.0 · 200+ stays"),
  welcomeReviewText: text("welcome_review_text").notNull().default("An unforgettable experience on the water."),
  welcomeReviewAttribution: text("welcome_review_attribution").notNull().default("Verified guest · Goa, 2024"),
  welcomeImage: text("welcome_image").notNull().default(""),
  packagesLabel: text("packages_label").notNull().default("Our Offerings"),
  packagesTitle: text("packages_title").notNull().default("Packages & Deals"),
  galleryLabel: text("gallery_label").notNull().default("A Glimpse Inside"),
  galleryTitle: text("gallery_title").notNull().default("Photo Gallery"),
  bannerLabel: text("banner_label").notNull().default("The Mhadeinest Way"),
  bannerTitle: text("banner_title").notNull().default("Experience Goa Like You Never Have Before"),
  bannerDescription: text("banner_description").notNull().default("Wake up on the river. Kayak at sunrise. Dine under the stars. Mhadeinest is your private floating retreat, away from the crowds."),
  bannerImage: text("banner_image").notNull().default(""),
  dbType: text("db_type").notNull().default("postgresql"),
  dbHost: text("db_host").notNull().default(""),
  dbPort: text("db_port").notNull().default("3306"),
  dbName: text("db_name").notNull().default(""),
  dbUser: text("db_user").notNull().default(""),
  dbPass: text("db_pass").notNull().default(""),
  deployDomain: text("deploy_domain").notNull().default(""),
  uploadRootPath: text("upload_root_path").notNull().default("/home/youruser/public_html/uploads"),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

export const insertSettingsSchema = createInsertSchema(settingsTable).omit({ id: true, updatedAt: true });
export type InsertSettings = z.infer<typeof insertSettingsSchema>;
export type Settings = typeof settingsTable.$inferSelect;

export const adminUsersTable = pgTable("admin_users", {
  id: serial("id").primaryKey(),
  username: text("username").notNull().unique(),
  passwordHash: text("password_hash").notNull(),
  role: text("role").notNull().default("admin"),
  displayName: text("display_name").notNull().default(""),
  email: text("email").notNull().default(""),
  phone: text("phone").notNull().default(""),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export type AdminUser = typeof adminUsersTable.$inferSelect;
